import {Metadata} from "next";
import {ReactNode} from "react";
import "@styles/tailwind.css";
import Header from "@components/header";

export const metadata: Metadata = {
	title: "EmberForge",
	description: "Generated by create next app", // TODO: Update this
};

export default function RootLayout({children}: Readonly<{children: ReactNode}>) {
	return (
		<html lang="en">
			<body className={"bg-stone-100 dark:bg-stone-950 text-black dark:text-white"}>
				<Header/>

				{children}
			</body>
		</html>
	);
}