import {Metadata} from "next";
import {ReactNode, Suspense} from "react";
import "@styles/globals.css";
import Header from "@components/header";
import StyledComponentsRegistry from "@/registry";

export const metadata: Metadata = {
	title: "EmberForge",
	description: "Generated by create next app", // TODO: Update this
};

export default function RootLayout({children}: Readonly<{children: ReactNode}>) {
	return (
		<html lang="en">
			<body>
				<StyledComponentsRegistry>
					<Header/>

					<Suspense>
						{children}
					</Suspense>
				</StyledComponentsRegistry>
			</body>
		</html>
	);
}